name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  PYTHONUNBUFFERED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download logs from artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          path: cloud-json
          workflow: update-image-data.yml
          repo: redhatcloudx/cloud-image-retriever

      - name: Get tree
        run: tree

      - name: Install requirements
        run: pip install pandas

      - name: Build static API files
        run: python generate_aws_idx.py

      - name: Check output
        run: tree

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
