name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download logs from artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          path: cloud-json
          workflow: update-image-data.yml

      - name: Get tree
        run: tree

      # - name: Set up Python 3.11
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: "3.11"

      # - name: Install
      #   run: |
      #     pipx install poetry
      #     poetry install

      # - name: Build static API files
      #   run: poetry run awsbuilder

      # - name: Check output
      #   run: du -hs public/*
