name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  PYTHONUNBUFFERED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download logs from artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          path: cloud-json
          workflow: update-image-data.yml
          repo: redhatcloudx/cloud-image-retriever

      - name: Get tree
        run: tree

      - name: Install requirements
        run: pip install pandas

      - name: Build static API files
        run: python generate_aws_idx.py

      - name: Check output
        run: tree public
